language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: rev6b4r+g9MBljTFyogz/74Gqh4gEQiki7pjhXhbcX/Fwu5Gk2GwVMRKiri9tkzLZQ8j+gr/a4N2M85W8e0PVItziSQKGfVRXeEMwcJBsv645Nrhcnf8yTNESFUrhybLs2H/5lp/BqBBl/kfs8s3kn9RytWNglAaqfBv59fnPqFzrVA7L/bBY/Tl8OzbIjF7Tf1M7wv/azmvc38Bogj6CpsQGrI8IwTLm1ld2dLb73LtHUuMnBKVZJ8upHhGCkC+mXP0kfQta28eaMLUXEjiwXWUjgXYGJgS5rBjLLwcMs5sfw8u+Shux/KKDHk0ISR/Vr3YQBhoSoIq4OoiO/Zlio56i2BUTaAZFZ4ddTWywteCNxX1lbYXdFe1jErH9fogEQn3Ghtq6PaBwW0NeDGSuEpyNljtV7x+ucxNAEbWTVp0ndj6R3FAqdkZFNssOilXf+psR+EDoJU7Tmg5I6yyqsw0Y1RZGhvMKWOfikePAi9MUWQRLHEBWtQpl/Xji9OlGkEbrFW9oNOLJV9VE4LlUKapMNNpQp0RsqnqsfirdzPNlWzwRoL+qUgMTEnwKD4KHCQvuqAdgDAdRZyaU8Em7ru/v3ipR0i+dp3kK/DAB4dKrJfyXgw3i7HCiyKQOmLIqjX/2aWiKxsIehh0/yJE916/Zyy3Kik+JZAtdIXQr84=
  on:
    tags: true
    repo: anton-b/alertlogic-sdk-definitions
    python: 3.8
